// <auto-generated />
using System;
using EntityWebSelect.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityWebSelect.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260629142631_InicializarBancoCorrigido")]
    partial class InicializarBancoCorrigido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityWebSelect.Model.ClienteModel", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DtNasc")
                        .HasColumnType("date")
                        .HasColumnName("DtNasc");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.HasKey("IdCliente");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("TBL_CLIENTE");

                    b.HasData(
                        new
                        {
                            IdCliente = 1,
                            Cpf = "123.456.789-00",
                            DtNasc = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Luiz"
                        });
                });

            modelBuilder.Entity("EntityWebSelect.Model.ItemPedidoModel", b =>
                {
                    b.Property<int>("IdItens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Itens");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItens"));

                    b.Property<string>("DescIten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescIten");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("idPedido");

                    b.Property<int>("QtdeEstoque")
                        .HasColumnType("int")
                        .HasColumnName("QtdeEstoque");

                    b.Property<decimal>("ValorUni")
                        .HasColumnType("money")
                        .HasColumnName("ValorUni");

                    b.HasKey("IdItens");

                    b.HasIndex("IdPedido");

                    b.ToTable("TBL_ITEM_PEDIDO");

                    b.HasData(
                        new
                        {
                            IdItens = 100,
                            DescIten = "Teclado Mecânico",
                            IdPedido = 10,
                            QtdeEstoque = 1,
                            ValorUni = 100.00m
                        },
                        new
                        {
                            IdItens = 101,
                            DescIten = "Mouse Pad Gamer",
                            IdPedido = 10,
                            QtdeEstoque = 1,
                            ValorUni = 50.00m
                        });
                });

            modelBuilder.Entity("EntityWebSelect.Model.PedidoModel", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime>("DtVenda")
                        .HasColumnType("date")
                        .HasColumnName("DtVenda");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.Property<decimal>("ValorTot")
                        .HasColumnType("money")
                        .HasColumnName("ValorTot");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.ToTable("TBL_PEDIDO");

                    b.HasData(
                        new
                        {
                            IdPedido = 10,
                            DtVenda = new DateTime(2026, 6, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 1,
                            ValorTot = 150.50m
                        });
                });

            modelBuilder.Entity("EntityWebSelect.Model.ItemPedidoModel", b =>
                {
                    b.HasOne("EntityWebSelect.Model.PedidoModel", "Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("EntityWebSelect.Model.PedidoModel", b =>
                {
                    b.HasOne("EntityWebSelect.Model.ClienteModel", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EntityWebSelect.Model.ClienteModel", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("EntityWebSelect.Model.PedidoModel", b =>
                {
                    b.Navigation("ItensPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
